// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnSsg5vTAGyBzcOdBCWuhpWEdt02jMsY',
    appId: '1:82252471486:web:b5b5e9067d3cc54a2952ef',
    messagingSenderId: '82252471486',
    projectId: 'travelapp-a0ed2',
    authDomain: 'travelapp-a0ed2.firebaseapp.com',
    storageBucket: 'travelapp-a0ed2.appspot.com',
    measurementId: 'G-5Y7V7N8G6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfAKLDNoVOsHdzxxVSfKY78jYcKutRhLs',
    appId: '1:82252471486:android:04f7ba15f69223312952ef',
    messagingSenderId: '82252471486',
    projectId: 'travelapp-a0ed2',
    storageBucket: 'travelapp-a0ed2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9JGrdv8CxJjPRvspXfvQP0IIpA9W6HDE',
    appId: '1:82252471486:ios:01d2b263be75c8572952ef',
    messagingSenderId: '82252471486',
    projectId: 'travelapp-a0ed2',
    storageBucket: 'travelapp-a0ed2.appspot.com',
    iosBundleId: 'com.example.travelKoreaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9JGrdv8CxJjPRvspXfvQP0IIpA9W6HDE',
    appId: '1:82252471486:ios:34150ba56c30cb442952ef',
    messagingSenderId: '82252471486',
    projectId: 'travelapp-a0ed2',
    storageBucket: 'travelapp-a0ed2.appspot.com',
    iosBundleId: 'com.example.travelKoreaApp.RunnerTests',
  );
}
